In [2]:
pip install numpy

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB 1.4 MB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 822.1 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 1.6 MB/s eta 0:00:10
    --------------------------------------- 0.3/15.8 MB 1.7 MB/s eta 0:00:09
   - -------------------------------------- 0.4/15.8 MB 2.5 MB/s eta 0:00:07
   - -------------------------------------- 0.7/15.8 MB 3.1 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/15.8 MB 3.6 MB/s eta 0:00:05
   --- ------------------------------------ 1.3/15.8 MB 4.0 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/15.8 MB 4.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.8/15.8 MB 4.1 MB/s eta 0:00:04
   ----- ---

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'



In [3]:
import numpy as np

In [8]:
random_int_array = np.random.randint(1, 50, size = 10)
random_int_array


dtype('int32')

In [9]:
random_int_array.dtype

dtype('int32')

In [10]:
random_int_array.size

10

In [11]:
np.ndim(random_int_array)

1

In [12]:
random_int_array_2 = np.random.randint(10, 100, size=(2, 5))
random_int_array_2

array([[72, 69, 12, 46, 99],
       [20, 48, 35, 40, 75]])

In [13]:
np.ndim(random_int_array_2)

2

In [16]:
random_int_array_3 = np.random.randint(1, 50, size=10)
random_int_array_3

array([32, 43,  6, 25, 30,  9,  3, 32, 33, 33])

In [1]:
random_int_array = np.random.randint(1, 50, size = 10)


NameError: name 'np' is not defined

In [2]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     --------------------------------- ------ 51.2/61.0 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 461.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 4.1 MB/s eta 0:00:04
    --------------------------------------- 0.3/15.8 MB 4.6 MB/s eta 0:00:04
   - -------------------------------------- 0.5/15.8 MB 4.2 MB/s eta 0:00:04
   - -------------------------------------- 0.5/15.8 MB 3.8 MB/s eta 0:00:05
   - -------------------------------------- 0.7/15.8 MB 3.5 MB/s eta 0:00:05
   -- ------------------------------------- 0.9/15.8 MB 3.6 MB/s eta 0:00:05
   -- ------------------------------------- 1.1/15.8 MB 3.7 MB/s eta 0:00:05
   --- ---------

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


NameError: name 'np' is not defined

In [ ]:
import numpy as np

In [8]:
random_int_array1 = np.random.randint(1, 50, size = 10)
random_int_array1


array([12, 44,  8,  9,  6, 26, 24, 47, 25, 39])

In [9]:
np.mean(random_int_array1)


24.0

In [12]:
my_arr1 = np.random.randint(1, 50, size = (3, 3))
my_arr1


array([[24, 32, 23],
       [20, 35,  4],
       [38, 21, 23]])

In [13]:
my_arr2 = np.random.randint(1, 50, size = (3, 3))
my_arr2

array([[23, 35, 18],
       [17,  4, 27],
       [30, 10, 39]])

In [16]:
big_arr = my_arr1 + my_arr2
big_arr

array([[47, 67, 41],
       [37, 39, 31],
       [68, 31, 62]])

In [19]:
avg = np.mean(big_arr)
avg

47.0

In [21]:
my_new_arr = np.random.randint(1, 100, size = 20)
my_new_arr

array([97, 57, 55, 88, 55, 18, 78, 33, 34, 94, 28, 45, 12, 90,  6, 10, 83,
       86, 17, 19])

In [24]:
x = my_new_arr > 50
good = my_new_arr[x]
good

array([97, 57, 55, 88, 55, 78, 94, 90, 83, 86])

In [25]:
nums = np.random.randint(1, 100, size = 10)
nums

array([52, 11, 62, 26,  7, 13, 30, 92, 48,  4])

In [28]:
np.random.shuffle(nums)
nums

array([30,  4, 92, 26, 13, 11, 48,  7, 62, 52])

In [30]:
x = nums%2 == 0
my_good = nums[x]
my_good

array([30,  4, 92, 26, 48, 62, 52])